version: '3'

services:
        dokuwiki:
                container_name: dokuwiki
                image: linuxserver/dokuwiki:version-2022-07-31a
                networks:
                        - nginx-proxy
                ports:
                        - 8003:80
                restart: unless-stopped
                environment:
                        VIRTUAL_HOST: ${HOST}
                        LETSENCRYPT_HOST: ${HOST}
                        LETSENCRYPT_EMAIL: ${EMAIL}
                volumes:
                        - dokuwiki_data:/config/dokuwiki/data
                        - dokuwiki_conf:/config/dokuwiki/conf
                        - dokuwiki_plugins:/config/dokuwiki/lib/plugins
                        - dokuwiki_tpl:/config/dokuwiki/lib/tpl
                        # - dokuwiki_logs:/var/log
networks:
        nginx-proxy:
                external: true
volumes:
        dokuwiki_data:
        dokuwiki_conf:
        dokuwiki_plugins:
        dokuwiki_tpl:
        dokuwiki_logs:
