FROM ampache/ampache@sha256:eef739dfef149af4a964e9702e5e0ef323f191c4be538c746ce2dce7a3a07042

sed -i 's|;local_web_path = "http://localhost/ampache"|local_web_path = "http://localhost:80"|g' ampache.cfg.php.dist
