version: '3'

services:
  nginx-proxy:
    image: nginx-proxy:1.0
    build: ./nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80/tcp"
      - "443:444"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-ssl:/etc/nginx/certs:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - nginx-proxy
    restart: always

  nginx-gen:
    image: jwilder/docker-gen:0.7.0
    # image: jwilder/docker-gen:0.9.0
    container_name: nginx-gen
    command: -notify-sighup nginx-proxy -wait 5s:30s -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-gen-tmpl:/etc/docker-gen/templates:rw
      - nginx-ssl:/etc/nginx/certs:ro
    links:
      - nginx-proxy
    networks:
      - nginx-proxy
    restart: always

  nginx-ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    container_name: nginx-ssl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-gen-tmpl:/etc/docker-gen/templates:ro
      - nginx-ssl:/etc/nginx/certs:rw
    environment:
      - ACME_CA_URI
      - "NGINX_DOCKER_GEN_CONTAINER=nginx-gen"
    links:
      - nginx-proxy
      - nginx-gen
    networks:
      - nginx-proxy
    restart: always

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:
  nginx-gen-tmpl:
  nginx-ssl:

networks:
  nginx-proxy:
    external: true
